# Generated by Django 4.2.2 on 2023-06-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='foto',
        ),
        migrations.AddField(
            model_name='imovel',
            name='dimensionamento',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='imovel',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='num_quartos',
            field=models.IntegerField(default=None),
        ),
    ]
