# Generated by Django 4.2.2 on 2023-06-29 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_remove_imovel_foto_imovel_dimensionamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='dimensionamento',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='imagens',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='num_quartos',
        ),
        migrations.AddField(
            model_name='imovel',
            name='aceita_animais',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cod_imovel',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_ativacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='limite_hospedes',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='qtd_banheiros',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_limpeza',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
            preserve_default=False,
        ),
    ]
