# Generated by Django 4.2.2 on 2023-06-29 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_remove_imovel_descricao_and_more'),
        ('anuncios', '0003_rename_data_fim_anuncios_data_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncios',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='anuncios',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='anuncios',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='anuncios',
            name='preco',
        ),
        migrations.AddField(
            model_name='anuncios',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='anuncios',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncios',
            name='nome_plataforma',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='anuncios',
            name='taxa_plataforma',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncios',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='imoveis.imovel'),
        ),
    ]
