# Generated by Django 4.2.2 on 2023-06-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0003_rename_data_fim_anuncios_data_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquilino', models.CharField(max_length=100)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.anuncios')),
            ],
        ),
    ]
