# Generated by Django 4.2.2 on 2023-06-29 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_data_entrada_reservas_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='codigo_reserva',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
